from __future__ import annotations
import json
import streamlit.components.v1 as components

def render_vibration_2dof_3d(data:dict,height:int=610):
    d=json.dumps(data,ensure_ascii=False,separators=(',',':'))
    html=f'''
<div id="v2d" style="height:{height}px;border:1px solid #ded7cc;border-radius:14px;overflow:hidden;background:#202126;position:relative">
<div style="position:absolute;z-index:4;left:13px;top:11px;background:#fff8edee;padding:8px 11px;border-radius:10px;font:13px system-ui;color:#25262a"><b>Vibración 2GDL</b><br><span id="msg"></span></div>
<div id="read" style="position:absolute;z-index:4;left:13px;bottom:11px;background:#202126dd;border:1px solid #515258;color:#f5ead7;padding:7px 10px;border-radius:9px;font:12px system-ui"></div>
<div style="position:absolute;z-index:4;right:11px;top:11px;display:flex;gap:5px;flex-wrap:wrap"><button id="play">Pausa</button><button id="front">Frente</button><button id="iso">Isométrica</button><button id="fit">Ajustar</button><button id="reset">Restablecer</button></div>
<canvas id="fb" width="1000" height="{height}" style="width:100%;height:100%"></canvas></div>
<style>#v2d button{{border:1px solid #c8752d;background:#fff8ed;color:#292a2e;border-radius:8px;padding:7px 9px;cursor:pointer}}</style>
<script type="module">
const D={d},root=document.getElementById('v2d'),cv=document.getElementById('fb'),msg=document.getElementById('msg'),read=document.getElementById('read');let paused=false;
function fb(){{const c=cv.getContext('2d'),W=cv.width,H=cv.height;c.fillStyle='#202126';c.fillRect(0,0,W,H);c.fillStyle='#c8752d';c.fillRect(70,H/2-100,25,200);c.strokeStyle='#d9c8ae';c.lineWidth=4;c.beginPath();c.moveTo(95,H/2);c.lineTo(320,H/2);c.stroke();c.fillStyle='#e8dfcf';c.fillRect(320,H/2-55,120,110);c.strokeStyle='#d9c8ae';c.beginPath();c.moveTo(440,H/2);c.lineTo(650,H/2);c.stroke();c.fillStyle='#e8dfcf';c.fillRect(650,H/2-45,105,90);msg.textContent='Vista de respaldo';}}fb();
try{{const THREE=await import('https://cdn.jsdelivr.net/npm/three@0.169.0/+esm');const {{OrbitControls}}=await import('https://cdn.jsdelivr.net/npm/three@0.169.0/examples/jsm/controls/OrbitControls.js/+esm');cv.style.display='none';const scene=new THREE.Scene();scene.background=new THREE.Color('#202126');const camera=new THREE.PerspectiveCamera(34,root.clientWidth/{height},.01,100);const renderer=new THREE.WebGLRenderer({{antialias:true}});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.setSize(root.clientWidth,{height});root.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.zoomToCursor=true;scene.add(new THREE.HemisphereLight('#fff8ec','#303136',2.2));const dl=new THREE.DirectionalLight('#fff',2);dl.position.set(5,7,8);scene.add(dl);
const G=new THREE.Group();scene.add(G);const wall=new THREE.Mesh(new THREE.BoxGeometry(.28,2.5,2.2),new THREE.MeshStandardMaterial({{color:'#c8752d'}}));wall.position.x=-3.7;G.add(wall);const rail=new THREE.Mesh(new THREE.BoxGeometry(7.7,.08,.14),new THREE.MeshStandardMaterial({{color:'#74777e'}}));rail.position.set(.1,-.82,0);G.add(rail);const mmat=new THREE.MeshStandardMaterial({{color:'#e7ddcc'}});function mkMass(s){{const g=new THREE.Group(),b=new THREE.Mesh(new THREE.BoxGeometry(s,s,s),mmat);g.add(b);g.add(new THREE.LineSegments(new THREE.EdgesGeometry(b.geometry),new THREE.LineBasicMaterial({{color:0x9c9488}})));G.add(g);return g}}const M1=mkMass(1.35),M2=mkMass(1.05);
function spring(xa,xb,y){{const pts=[];for(let i=0;i<=150;i++){{const q=i/150;let x=xa+(xb-xa)*q,z=0;if(i>5&&i<145)z=.18*Math.sin(22*Math.PI*q);pts.push(new THREE.Vector3(x,y,z))}}return new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({{color:'#d9c8ae'}}))}}let s1=null,s2=null;const F=new THREE.ArrowHelper(new THREE.Vector3(1,0,0),new THREE.Vector3(),1,0xf28e1c,.22,.12);G.add(F);
const grid=new THREE.GridHelper(11,11,0x46474c,0x303136);grid.position.set(.1,-1.45,0);scene.add(grid);const t=D.t||[],x1=D.x1||[],x2=D.x2||[],ff=D.force||[];const dur=Math.max(D.duration||6,1e-6),amp=D.visual_amp||1,speed=D.speed||1;const xmax=Math.max(...x1.map(Math.abs),...x2.map(Math.abs),1e-9),fmax=Math.max(...ff.map(Math.abs),1e-9);let tm=0,last=performance.now();function sample(a,tt){{if(!a.length)return 0;const u=((tt%dur)/dur)*(a.length-1),i=Math.floor(u),j=Math.min(a.length-1,i+1),q=u-i;return a[i]*(1-q)+a[j]*q}}function update(dt){{if(!paused)tm+=dt*speed;const a=sample(x1,tm),b=sample(x2,tm),fv=sample(ff,tm);M1.position.set(.1+(a/xmax)*1.05*amp,0,0);M2.position.set(3.0+(b/xmax)*1.05*amp,0,0);if(s1)G.remove(s1);if(s2)G.remove(s2);s1=spring(-3.55,M1.position.x-.7,.42);s2=spring(M1.position.x+.7,M2.position.x-.55,.42);G.add(s1);G.add(s2);const sg=Math.sign(fv)||1,len=.25+1.05*Math.min(1,Math.abs(fv)/fmax);F.position.set(M1.position.x,1.05,0);F.setDirection(new THREE.Vector3(sg,0,0));F.setLength(len,.22,.12);F.visible=D.show_force!==false;read.textContent=`t = ${{(tm%dur).toFixed(2)}} s · x₁ = ${{(a*1000).toFixed(2)}} mm · x₂ = ${{(b*1000).toFixed(2)}} mm`;}}function front(){{camera.position.set(0,.1,9.6);controls.target.set(0,0,0);controls.update()}}function iso(){{camera.position.set(5,3.5,7.7);controls.target.set(0,0,0);controls.update()}}function fit(){{const b=new THREE.Box3().setFromObject(G),sz=b.getSize(new THREE.Vector3()),ct=b.getCenter(new THREE.Vector3()),md=Math.max(sz.x,sz.y,sz.z,1),f=camera.fov*Math.PI/180,dist=md/(2*Math.tan(f/2))*1.3,dir=new THREE.Vector3().subVectors(camera.position,controls.target).normalize();controls.target.copy(ct);camera.position.copy(ct.clone().add(dir.multiplyScalar(dist)));controls.update()}}function reset(){{front();fit()}}reset();document.getElementById('front').onclick=()=>{{front();fit()}};document.getElementById('iso').onclick=()=>{{iso();fit()}};document.getElementById('fit').onclick=fit;document.getElementById('reset').onclick=reset;document.getElementById('play').onclick=e=>{{paused=!paused;e.target.textContent=paused?'Reproducir':'Pausa'}};msg.textContent=D.label||'Respuesta 2GDL';function loop(now){{const dt=Math.min(.05,(now-last)/1000);last=now;update(dt);controls.update();renderer.render(scene,camera);requestAnimationFrame(loop)}}requestAnimationFrame(loop);}}catch(e){{msg.textContent='Vista de respaldo · Three.js no disponible';}}
</script>'''
    components.html(html,height=height,scrolling=False)
