from __future__ import annotations

CASES = {
    # -----------------------------------------------------------------
    # 1–4 · Voladizo / empotrada-libre
    # -----------------------------------------------------------------
    "cantilever_end_load": {
        "family": "Voladizo / empotrada–libre",
        "title": "Carga puntual en el extremo",
        "short": "Voladizo · carga puntual al extremo",
        "load_type": "point_end",
        "parameters": ["L", "F"],
        "classification": "Isostática",
        "v_shape": "Constante entre el empotramiento y el extremo libre.",
        "m_shape": "Lineal: máximo valor absoluto en el empotramiento y cero en el extremo libre.",
        "insight": "La carga puntual produce un salto de cortante en el extremo. Dentro del tramo V es constante, por lo que M varía linealmente.",
    },
    "cantilever_point_load": {
        "family": "Voladizo / empotrada–libre",
        "title": "Carga puntual intermedia",
        "short": "Voladizo · carga puntual intermedia",
        "load_type": "point",
        "parameters": ["L", "F", "a"],
        "a_mode": "position",
        "classification": "Isostática",
        "v_shape": "Constante desde el empotramiento hasta la carga; cero desde la carga al extremo libre.",
        "m_shape": "Lineal en el tramo cargado y nulo después de la carga.",
        "insight": "La porción situada más allá de la carga no transmite cortante ni momento interno en este caso ideal.",
    },
    "cantilever_udl": {
        "family": "Voladizo / empotrada–libre",
        "title": "Carga uniformemente distribuida",
        "short": "Voladizo · carga distribuida uniforme",
        "load_type": "udl",
        "parameters": ["L", "w"],
        "classification": "Isostática",
        "v_shape": "Lineal.",
        "m_shape": "Parabólico.",
        "insight": "Una carga distribuida constante genera una variación lineal del cortante y, al integrar V(x), una variación parabólica del momento.",
    },
    "cantilever_end_moment": {
        "family": "Voladizo / empotrada–libre",
        "title": "Momento aplicado en el extremo",
        "short": "Voladizo · momento al extremo",
        "load_type": "moment_end",
        "parameters": ["L", "M0"],
        "classification": "Isostática",
        "v_shape": "Nulo en toda la viga.",
        "m_shape": "Constante en toda la longitud.",
        "insight": "Un par puro no introduce fuerza transversal. Por eso V(x)=0 y el momento interno permanece constante.",
    },

    # -----------------------------------------------------------------
    # 5–10 · Simplemente apoyadas
    # -----------------------------------------------------------------
    "simple_center_load": {
        "family": "Simplemente apoyada",
        "title": "Carga puntual centrada",
        "short": "Simplemente apoyada · carga central",
        "load_type": "point_center",
        "parameters": ["L", "F"],
        "classification": "Isostática",
        "v_shape": "Dos niveles constantes, con salto en el centro.",
        "m_shape": "Triangular, con máximo en el centro.",
        "insight": "El máximo momento aparece donde el cortante cambia de signo. La simetría hace iguales las dos reacciones.",
    },
    "simple_point_load": {
        "family": "Simplemente apoyada",
        "title": "Carga puntual en posición a",
        "short": "Simplemente apoyada · carga intermedia",
        "load_type": "point",
        "parameters": ["L", "F", "a"],
        "a_mode": "position",
        "classification": "Isostática",
        "v_shape": "Constante por tramos, con salto en la carga.",
        "m_shape": "Lineal por tramos y continuo en el punto de aplicación.",
        "insight": "La pendiente de M(x) cambia al cruzar la carga porque el cortante cambia de valor.",
    },
    "simple_udl": {
        "family": "Simplemente apoyada",
        "title": "Carga uniformemente distribuida",
        "short": "Simplemente apoyada · carga distribuida",
        "load_type": "udl",
        "parameters": ["L", "w"],
        "classification": "Isostática",
        "v_shape": "Lineal y cruza por cero en el centro.",
        "m_shape": "Parabólico, con máximo en el centro.",
        "insight": "Donde V(x)=0 aparece un extremo de M(x); para este caso simétrico corresponde al máximo momento flector.",
    },
    "simple_point_moment": {
        "family": "Simplemente apoyada",
        "title": "Momento concentrado en posición a",
        "short": "Simplemente apoyada · momento concentrado",
        "load_type": "moment",
        "parameters": ["L", "M0", "a"],
        "a_mode": "position",
        "classification": "Isostática",
        "v_shape": "Constante en toda la luz.",
        "m_shape": "Lineal por tramos, con un salto igual al momento aplicado.",
        "insight": "Un momento concentrado no produce salto de cortante; produce directamente una discontinuidad en M(x).",
    },
    "simple_twin_loads": {
        "family": "Simplemente apoyada",
        "title": "Dos cargas puntuales simétricas",
        "short": "Simplemente apoyada · dos cargas simétricas",
        "load_type": "twin_points",
        "parameters": ["L", "F", "a"],
        "a_mode": "symmetric_offset",
        "classification": "Isostática",
        "v_shape": "Positivo, luego cero entre las cargas y negativo antes del apoyo derecho.",
        "m_shape": "Lineal–constante–lineal; existe una meseta de momento entre las dos cargas.",
        "insight": "Entre las dos cargas el cortante es cero, por lo que el momento permanece constante: la pendiente de M(x) es nula.",
    },
    "simple_overhang_load": {
        "family": "Simplemente apoyada",
        "title": "Carga puntual en voladizo exterior",
        "short": "Simplemente apoyada · carga en voladizo exterior",
        "load_type": "overhang_point",
        "parameters": ["L", "F", "a"],
        "a_mode": "overhang_length",
        "classification": "Isostática",
        "v_shape": "Constante negativo entre apoyos y positivo en el voladizo exterior.",
        "m_shape": "Negativo entre el apoyo izquierdo y el extremo cargado; cero en el apoyo izquierdo y en el extremo libre.",
        "insight": "La reacción del apoyo izquierdo cambia de sentido. El caso muestra que una viga simplemente apoyada puede desarrollar momento negativo cuando existe un voladizo cargado.",
    },

    # -----------------------------------------------------------------
    # 11–13 · Empotrada + apoyo simple
    # -----------------------------------------------------------------
    "propped_center_load": {
        "family": "Empotrada + apoyo simple",
        "title": "Carga puntual centrada",
        "short": "Empotrada + apoyo · carga central",
        "load_type": "point_center",
        "parameters": ["L", "F"],
        "classification": "Hiperestática · grado 1",
        "v_shape": "Constante por tramos, con salto en la carga.",
        "m_shape": "Lineal por tramos: momento negativo en el empotramiento y positivo en la zona interior.",
        "insight": "Aparece un punto de contraflexión porque el empotramiento introduce momento negativo, mientras la zona central desarrolla momento positivo.",
    },
    "propped_point_load": {
        "family": "Empotrada + apoyo simple",
        "title": "Carga puntual en posición a",
        "short": "Empotrada + apoyo · carga intermedia",
        "load_type": "point",
        "parameters": ["L", "F", "a"],
        "a_mode": "position",
        "classification": "Hiperestática · grado 1",
        "v_shape": "Constante por tramos, con salto en la carga.",
        "m_shape": "Lineal por tramos, con momento negativo en el empotramiento.",
        "insight": "La compatibilidad de deformaciones determina la reacción adicional del apoyo simple; por eso las reacciones no se obtienen solo con equilibrio estático.",
    },
    "propped_udl": {
        "family": "Empotrada + apoyo simple",
        "title": "Carga uniformemente distribuida",
        "short": "Empotrada + apoyo · carga distribuida",
        "load_type": "udl",
        "parameters": ["L", "w"],
        "classification": "Hiperestática · grado 1",
        "v_shape": "Lineal.",
        "m_shape": "Parabólico, con región negativa junto al empotramiento y positiva hacia el interior.",
        "insight": "La continuidad y la restricción de giro del empotramiento generan un momento negativo de apoyo y un punto de contraflexión.",
    },

    # -----------------------------------------------------------------
    # 14–16 · Empotrada-empotrada
    # -----------------------------------------------------------------
    "fixed_center_load": {
        "family": "Empotrada–empotrada",
        "title": "Carga puntual centrada",
        "short": "Empotrada–empotrada · carga central",
        "load_type": "point_center",
        "parameters": ["L", "F"],
        "classification": "Hiperestática · grado 2",
        "v_shape": "Dos niveles constantes y simétricos.",
        "m_shape": "Negativo en ambos empotramientos y positivo en el centro.",
        "insight": "Los dos empotramientos restringen el giro. Esto reduce el máximo momento positivo central, pero introduce momentos negativos en los extremos.",
    },
    "fixed_point_load": {
        "family": "Empotrada–empotrada",
        "title": "Carga puntual en posición a",
        "short": "Empotrada–empotrada · carga intermedia",
        "load_type": "point",
        "parameters": ["L", "F", "a"],
        "a_mode": "position",
        "classification": "Hiperestática · grado 2",
        "v_shape": "Constante por tramos, con salto en la carga.",
        "m_shape": "Lineal por tramos con momentos negativos en ambos empotramientos.",
        "insight": "La posición de la carga redistribuye tanto las reacciones verticales como los momentos de empotramiento en los dos extremos.",
    },
    "fixed_udl": {
        "family": "Empotrada–empotrada",
        "title": "Carga uniformemente distribuida",
        "short": "Empotrada–empotrada · carga distribuida",
        "load_type": "udl",
        "parameters": ["L", "w"],
        "classification": "Hiperestática · grado 2",
        "v_shape": "Lineal y antisimétrico respecto del centro.",
        "m_shape": "Parabólico, negativo en los extremos y positivo en la zona central.",
        "insight": "La restricción de giro en ambos extremos genera momentos negativos de apoyo y dos puntos de contraflexión.",
    },
}

FAMILIES = {
    "Voladizo / empotrada–libre": [
        "cantilever_end_load",
        "cantilever_point_load",
        "cantilever_udl",
        "cantilever_end_moment",
    ],
    "Simplemente apoyada": [
        "simple_center_load",
        "simple_point_load",
        "simple_udl",
        "simple_point_moment",
        "simple_twin_loads",
        "simple_overhang_load",
    ],
    "Empotrada + apoyo simple": [
        "propped_center_load",
        "propped_point_load",
        "propped_udl",
    ],
    "Empotrada–empotrada": [
        "fixed_center_load",
        "fixed_point_load",
        "fixed_udl",
    ],
}
