from __future__ import annotations
import json
import streamlit.components.v1 as components

def render_torsion_3d(data:dict,height:int=650):
    d=json.dumps(data,ensure_ascii=False,separators=(',',':'))
    html=f'''<div id="tor3d" style="height:{height}px;border:1px solid #ded7cc;border-radius:14px;overflow:hidden;background:#202126;position:relative">
<div style="position:absolute;z-index:3;left:14px;top:12px;background:#fff8edee;padding:8px 11px;border-radius:10px;font:13px system-ui;color:#25262a"><b>Torsión 3D</b><br><span id="tormsg"></span></div>
<div style="position:absolute;z-index:3;right:12px;top:12px;display:flex;gap:6px"><button id="front">Frente</button><button id="iso">Isométrica</button><button id="end">Sección</button></div>
<canvas id="fb" width="900" height="620" style="width:100%;height:100%"></canvas></div>
<style>#tor3d button{{border:1px solid #c8752d;background:#fff8ed;color:#292a2e;border-radius:8px;padding:7px 9px;cursor:pointer}}</style>
<script type="module">
const D={d},root=document.getElementById('tor3d'),cv=document.getElementById('fb'),msg=document.getElementById('tormsg');
function fallback(){{const c=cv.getContext('2d'),W=cv.width,H=cv.height;c.fillStyle='#202126';c.fillRect(0,0,W,H);const x0=130,x1=770,y=310,r=90;c.strokeStyle='#f28e1c';c.lineWidth=4;for(let i=0;i<=12;i++){{let t=i/12,x=x0+(x1-x0)*t,a=D.phi_display*t;c.save();c.translate(x,y);c.rotate(-a);c.strokeRect(-20,-r,40,2*r);c.restore()}}msg.textContent='Vista de respaldo · giro amplificado';}}fallback();
try{{const THREE=await import('https://cdn.jsdelivr.net/npm/three@0.169.0/+esm');const {{OrbitControls}}=await import('https://cdn.jsdelivr.net/npm/three@0.169.0/examples/jsm/controls/OrbitControls.js/+esm');cv.style.display='none';const scene=new THREE.Scene();scene.background=new THREE.Color('#202126');const camera=new THREE.PerspectiveCamera(35,root.clientWidth/{height},.01,100);const renderer=new THREE.WebGLRenderer({{antialias:true}});renderer.setSize(root.clientWidth,{height});root.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);scene.add(new THREE.HemisphereLight('#fff8ec','#303136',2.3));const dl=new THREE.DirectionalLight('#fff',2);dl.position.set(4,5,6);scene.add(dl);const L=7,phi=D.phi_display,s=D.section||{{kind:'custom'}};let H=1.15,B=.8,TW=.14,TF=.16;if(s.h&&s.b){{const sc=1.2/Math.max(s.h,s.b);H=s.h*sc;B=s.b*sc;TW=(s.tw||s.b*.12)*sc;TF=(s.tf||s.h*.12)*sc}}else if(s.kind==='rect'){{const sc=1.2/Math.max(s.h,s.b);H=s.h*sc;B=s.b*sc}}else if(s.d||s.do){{H=B=1.15}}
function outline(color='#d9c8ae'){{const g=new THREE.Group(),mat=new THREE.LineBasicMaterial({{color}});function loop(arr){{const pp=arr.map(a=>new THREE.Vector3(0,a[1],a[0]));pp.push(pp[0].clone());g.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pp),mat))}}if(s.kind==='rect'||s.kind==='custom')loop([[-B/2,-H/2],[B/2,-H/2],[B/2,H/2],[-B/2,H/2]]);else if(s.kind==='i_profile')loop([[-B/2,-H/2],[B/2,-H/2],[B/2,-H/2+TF],[TW/2,-H/2+TF],[TW/2,H/2-TF],[B/2,H/2-TF],[B/2,H/2],[-B/2,H/2],[-B/2,H/2-TF],[-TW/2,H/2-TF],[-TW/2,-H/2+TF],[-B/2,-H/2+TF]]);else if(s.kind==='channel')loop([[-B/2,-H/2],[B/2,-H/2],[B/2,-H/2+TF],[-B/2+TW,-H/2+TF],[-B/2+TW,H/2-TF],[B/2,H/2-TF],[B/2,H/2],[-B/2,H/2]]);else{{const ro=.57,ri=s.kind==='tube'&&s.di&&s.do?ro*s.di/s.do:0;for(const rr of [ro,ri])if(rr>0){{const a=[];for(let j=0;j<65;j++){{let q=j/64*Math.PI*2;a.push(new THREE.Vector3(0,rr*Math.sin(q),rr*Math.cos(q)))}}g.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(a),mat))}}}}return g}}
for(let i=0;i<=18;i++){{let t=i/18,o=outline(i===18?'#f28e1c':'#cdbda6');o.position.x=L*t;o.rotation.x=phi*t;scene.add(o)}}
// material generator lines connect homologous points approximately for visual reading
for(let a=0;a<4;a++){{const pts=[];for(let i=0;i<=100;i++){{let t=i/100,q=a*Math.PI/2+phi*t;let ry=H*.46,rz=B*.46;pts.push(new THREE.Vector3(L*t,ry*Math.sin(q),rz*Math.cos(q)))}}scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({{color:a===0?'#f28e1c':'#4b4c50'}})))}}
const tor=new THREE.Mesh(new THREE.TorusGeometry(1.0,.045,12,48,Math.PI*1.6),new THREE.MeshStandardMaterial({{color:'#f28e1c'}}));tor.rotation.y=Math.PI/2;tor.position.x=L+.15;scene.add(tor);const grid=new THREE.GridHelper(10,10,0x4a4b50,0x34353a);grid.position.x=L/2;scene.add(grid);function iso(){{camera.position.set(10,5,8);controls.target.set(3.5,0,0);controls.update()}}function front(){{camera.position.set(3.5,0,10);controls.target.set(3.5,0,0);controls.update()}}function end(){{camera.position.set(10,0,0);controls.target.set(7,0,0);controls.update()}}iso();document.getElementById('front').onclick=front;document.getElementById('iso').onclick=iso;document.getElementById('end').onclick=end;msg.textContent='Sección real · giro amplificado';function loop(){{renderer.render(scene,camera);requestAnimationFrame(loop)}}loop();}}catch(e){{msg.textContent='Vista de respaldo · Three.js no disponible';}}
</script>'''
    components.html(html,height=height,scrolling=False)
