from __future__ import annotations
import json
import streamlit.components.v1 as components

def render_column_3d(data:dict,height:int=650):
    payload=json.dumps(data,ensure_ascii=False,separators=(',',':'))
    html=f'''<div id="col3d" style="height:{height}px;border:1px solid #ded7cc;border-radius:14px;overflow:hidden;background:#202126;position:relative">
<div style="position:absolute;z-index:2;left:14px;top:12px;background:#fff8edee;padding:8px 11px;border-radius:10px;font:13px system-ui;color:#25262a"><b>Columna 3D</b><br><span id="colmsg"></span></div>
<div style="position:absolute;z-index:2;right:12px;top:12px;display:flex;gap:6px;flex-wrap:wrap"><button id="front">Frente</button><button id="iso">Isométrica</button><button id="section">Sección</button></div>
<canvas id="fallback" width="900" height="620" style="width:100%;height:100%"></canvas></div>
<style>#col3d button{{border:1px solid #c8752d;background:#fff8ed;color:#292a2e;border-radius:8px;padding:7px 9px;cursor:pointer}}</style>
<script type="module">
const D={payload}; const root=document.getElementById('col3d'),cv=document.getElementById('fallback'),msg=document.getElementById('colmsg');
function mode(t){{if(!D.show_buckling)return 0;if(D.end==='Articulada – articulada')return Math.sin(Math.PI*t);if(D.end==='Empotrada – libre')return 1-Math.cos(Math.PI*t/2);if(D.end==='Empotrada – empotrada')return (1-Math.cos(2*Math.PI*t))/2;return t*t*(1-t)*6.75}}
function fallback(){{const c=cv.getContext('2d'),W=cv.width,H=cv.height;c.clearRect(0,0,W,H);c.fillStyle='#202126';c.fillRect(0,0,W,H);const x=W*.5,y0=H*.82,y1=H*.18,amp=Math.min(120,30+120*Math.min(D.ratio,1.2));c.strokeStyle='#f28e1c';c.lineWidth=16;c.beginPath();for(let i=0;i<=120;i++){{let t=i/120,x0=x+amp*mode(t),yy=y0+(y1-y0)*t;i?c.lineTo(x0,yy):c.moveTo(x0,yy)}}c.stroke();c.strokeStyle='#fff2db';c.setLineDash([8,8]);c.lineWidth=2;c.beginPath();c.moveTo(x,y0);c.lineTo(x,y1);c.stroke();c.setLineDash([]);msg.textContent='Vista esquemática · deformada amplificada';}}fallback();
try{{const THREE=await import('https://cdn.jsdelivr.net/npm/three@0.169.0/+esm');const {{OrbitControls}}=await import('https://cdn.jsdelivr.net/npm/three@0.169.0/examples/jsm/controls/OrbitControls.js/+esm');cv.style.display='none';const scene=new THREE.Scene();scene.background=new THREE.Color('#202126');const camera=new THREE.PerspectiveCamera(35,root.clientWidth/{height},.01,100);const renderer=new THREE.WebGLRenderer({{antialias:true}});renderer.setSize(root.clientWidth,{height});root.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);scene.add(new THREE.HemisphereLight('#fff8ec','#303136',2.3));const dl=new THREE.DirectionalLight('#fff',2);dl.position.set(4,6,5);scene.add(dl);const L=6,amp=.85,pts=[];for(let i=0;i<=90;i++){{let t=i/90;pts.push(new THREE.Vector3(amp*mode(t),L*t,0))}}const center=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({{color:'#f28e1c'}}));scene.add(center);
const s=D.section||{{kind:'custom'}};let H=.58,B=.42,TW=.09,TF=.10;if(s.h&&s.b){{const sc=.65/Math.max(s.h,s.b);H=s.h*sc;B=s.b*sc;TW=(s.tw||s.b*.12)*sc;TF=(s.tf||s.h*.12)*sc}}else if(s.kind==='rect'){{const sc=.65/Math.max(s.h,s.b);H=s.h*sc;B=s.b*sc}}else if(s.d){{H=B=.62}}
function outline(){{const g=new THREE.Group(),mat=new THREE.LineBasicMaterial({{color:'#e6d6be'}});function loop(arr){{const pp=arr.map(a=>new THREE.Vector3(a[0],0,a[1]));pp.push(pp[0].clone());g.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pp),mat))}}if(s.kind==='rect'||s.kind==='custom')loop([[-B/2,-H/2],[B/2,-H/2],[B/2,H/2],[-B/2,H/2]]);else if(s.kind==='i_profile'){{loop([[-B/2,-H/2],[B/2,-H/2],[B/2,-H/2+TF],[TW/2,-H/2+TF],[TW/2,H/2-TF],[B/2,H/2-TF],[B/2,H/2],[-B/2,H/2],[-B/2,H/2-TF],[-TW/2,H/2-TF],[-TW/2,-H/2+TF],[-B/2,-H/2+TF]])}}else if(s.kind==='channel'){{loop([[-B/2,-H/2],[B/2,-H/2],[B/2,-H/2+TF],[-B/2+TW,-H/2+TF],[-B/2+TW,H/2-TF],[B/2,H/2-TF],[B/2,H/2],[-B/2,H/2]])}}else{{const ro=B/2,ri=s.kind==='tube'&&s.di&&s.do?ro*s.di/s.do:0;for(const rr of [ro,ri])if(rr>0){{const a=[];for(let j=0;j<49;j++){{let q=j/48*Math.PI*2;a.push(new THREE.Vector3(rr*Math.cos(q),0,rr*Math.sin(q)))}}g.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(a),mat))}}}}return g}}
for(let i=0;i<=12;i++){{let t=i/12,x=amp*mode(t),y=L*t;let dt=.002,dx=(mode(Math.min(1,t+dt))-mode(Math.max(0,t-dt)))/(2*dt)*amp/L,ang=-Math.atan(dx);const o=outline();o.rotation.z=ang;o.position.set(x,y,0);scene.add(o)}}
const axis=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,0,0),new THREE.Vector3(0,L,0)]),new THREE.LineDashedMaterial({{color:'#8c8d92',dashSize:.18,gapSize:.12}}));axis.computeLineDistances();scene.add(axis);function fixedPlate(y){{const m=new THREE.Mesh(new THREE.BoxGeometry(1.3,.12,1.1),new THREE.MeshStandardMaterial({{color:'#c8752d',roughness:.75}}));m.position.set(0,y,0);scene.add(m)}}function pinMark(y){{const cone=new THREE.Mesh(new THREE.ConeGeometry(.42,.48,4),new THREE.MeshStandardMaterial({{color:'#c8752d',roughness:.75}}));cone.position.set(0,y,0);if(y>L/2)cone.rotation.z=Math.PI;scene.add(cone)}}
if(D.end.startsWith('Empotrada'))fixedPlate(-.12);else pinMark(-.26);if(D.end.endsWith('empotrada'))fixedPlate(L+.12);else if(D.end.endsWith('articulada'))pinMark(L+.26);
for(let k=-1;k<=1;k++)scene.add(new THREE.ArrowHelper(new THREE.Vector3(0,-1,0),new THREE.Vector3(k*.28,L+.8,0),.7,0xf28e1c,.15,.08));const grid=new THREE.GridHelper(5,10,0x4a4b50,0x34353a);scene.add(grid);function front(){{camera.position.set(8,3,0);controls.target.set(0,3,0);controls.update()}}function iso(){{camera.position.set(8,4.5,8);controls.target.set(0,3,0);controls.update()}}function sec(){{camera.position.set(.85*mode(.5),3,6);controls.target.set(.85*mode(.5),3,0);controls.update()}}front();document.getElementById('front').onclick=front;document.getElementById('iso').onclick=iso;document.getElementById('section').onclick=sec;msg.textContent='Perfil real · modo de pandeo amplificado';function loop(){{renderer.render(scene,camera);requestAnimationFrame(loop)}}loop();}}catch(e){{msg.textContent='Vista de respaldo · Three.js no disponible';}}
</script>'''
    components.html(html,height=height,scrolling=False)
