from __future__ import annotations

PORTS = {
    "P": "Puerto de presión / alimentación desde la bomba",
    "T": "Retorno principal al depósito",
    "A": "Puerto de trabajo hacia una cámara o sentido del actuador",
    "B": "Segundo puerto de trabajo hacia el actuador",
    "X": "Alimentación externa de pilotaje",
    "Y": "Drenaje o descarga externa del pilotaje",
    "L": "Drenaje de fugas / carcasa hacia depósito",
}

READING_RULES = [
    ("1", "Ubique la fuente", "Depósito, motor, bomba y línea de presión."),
    ("2", "Separe mando y potencia", "Qué genera la señal y qué elemento maneja la energía hidráulica."),
    ("3", "Identifique protección", "Alivio, filtros, acumuladores, medición y acondicionamiento."),
    ("4", "Lea el control", "Direccionales, presión, caudal y bloqueo; parta siempre por su condición de reposo."),
    ("5", "Encuentre el actuador", "Cilindro o motor; determine qué puerto produce cada movimiento."),
    ("6", "Trace cada estado", "Siga físicamente la ruta P → válvula → actuador → T."),
    ("7", "Prediga antes de medir", "Presión, caudal, movimiento y puntos de prueba esperados."),
]

SYMBOL_LIBRARY = {
    "Línea principal": {
        "category": "Líneas y conexiones",
        "symbol": "main_line",
        "function": "Transporta el caudal principal y, con él, potencia hidráulica entre los componentes del circuito.",
        "ports": "No aplica",
        "rest": "No tiene estado de reposo.",
        "reading": "Sígala para reconstruir la ruta de energía. No la confunda con líneas de pilotaje o drenaje.",
        "field": "Revise mangueras/tuberías, racores, estrangulamientos, fugas, aplastamientos y conexiones erróneas.",
        "failures": ["fuga externa", "restricción", "manguera colapsada", "conexión incorrecta"],
        "applications": ["alimentación", "retorno", "líneas de trabajo"],
        "principle": "La caída de presión aparece cuando el flujo atraviesa resistencias del circuito.",
    },
    "Línea de pilotaje": {
        "category": "Líneas y conexiones",
        "symbol": "pilot_line",
        "function": "Transporta una señal hidráulica de mando que desplaza o modula otro componente.",
        "ports": "X u otra conexión de control",
        "rest": "Depende de la lógica del circuito.",
        "reading": "Interprétela como una señal de control, no como la ruta principal de potencia.",
        "field": "Una restricción, fuga o presión insuficiente puede impedir la conmutación de una válvula pilotada.",
        "failures": ["pilotaje insuficiente", "línea obstruida", "fuga", "conexión cruzada"],
        "applications": ["válvulas pilotadas", "desbloqueo", "secuencia"],
        "principle": "Una pequeña señal de presión puede gobernar un componente que controla un caudal mucho mayor.",
    },
    "Línea de drenaje": {
        "category": "Líneas y conexiones",
        "symbol": "drain_line",
        "function": "Devuelve al depósito fugas internas, aceite de carcasa o fluido de cámaras de control.",
        "ports": "Y / L según el componente",
        "rest": "Debe mantenerse con baja contrapresión.",
        "reading": "Compruebe que termina correctamente en depósito y que no se confunde con una línea de pilotaje.",
        "field": "La contrapresión puede modificar ajustes, sellos o el funcionamiento de válvulas y motores.",
        "failures": ["contrapresión", "línea tapada", "retorno común mal diseñado", "fuga excesiva"],
        "applications": ["carcasas", "pilotaje", "válvulas de presión"],
        "principle": "El drenaje no es un detalle auxiliar: puede ser condición necesaria para que el componente funcione correctamente.",
    },
    "Depósito": {
        "category": "Fuente y acondicionamiento",
        "symbol": "reservoir",
        "function": "Almacena el fluido y sirve como referencia del retorno. También ayuda a desairear, decantar contaminantes y disipar calor.",
        "ports": "Succión, retorno y drenajes",
        "rest": "Elemento pasivo permanente del sistema.",
        "reading": "Use el depósito como punto de referencia para cerrar las rutas de retorno y drenaje.",
        "field": "Nivel, aireación, espuma, contaminación, temperatura, respiradero, succión y retorno bajo/sobre nivel.",
        "failures": ["nivel bajo", "aireación", "contaminación", "sobretemperatura"],
        "applications": ["central hidráulica", "retornos", "drenajes"],
        "principle": "Una bomba necesita una alimentación adecuada; problemas en succión pueden producir cavitación y pérdida de caudal.",
    },
    "Bomba de desplazamiento fijo": {
        "category": "Fuente y acondicionamiento",
        "symbol": "pump_fixed",
        "function": "Convierte energía mecánica en flujo hidráulico. Su desplazamiento geométrico por revolución es esencialmente fijo.",
        "ports": "Succión y P",
        "rest": "Mientras gira, intenta desplazar caudal; la presión depende de la resistencia que encuentra.",
        "reading": "El triángulo apunta hacia afuera: el componente entrega energía al fluido.",
        "field": "Caudal real, ruido, cavitación, aireación, drenaje, temperatura, succión y contaminación.",
        "failures": ["cavitación", "desgaste", "fuga interna", "aireación"],
        "applications": ["engranajes", "paletas", "pistones fijos"],
        "principle": "La bomba genera flujo; la carga y las restricciones hacen que se desarrolle presión.",
    },
    "Bomba de desplazamiento variable": {
        "category": "Fuente y acondicionamiento",
        "symbol": "pump_variable",
        "function": "Convierte energía mecánica en flujo y permite variar el desplazamiento geométrico para modificar el caudal entregado.",
        "ports": "Succión, P y posibles puertos de control/drenaje",
        "rest": "Depende del sistema de control de desplazamiento.",
        "reading": "La flecha diagonal indica que el parámetro principal del componente es ajustable o variable.",
        "field": "Control de desplazamiento, compensador, pilotaje, drenaje de carcasa, temperatura y contaminación.",
        "failures": ["desajuste del compensador", "fuga interna", "pilotaje deficiente", "drenaje alto"],
        "applications": ["presión compensada", "load sensing", "circuitos de caudal variable"],
        "principle": "Modificar desplazamiento permite adaptar el caudal a la demanda del sistema.",
    },
    "Filtro": {
        "category": "Fuente y acondicionamiento",
        "symbol": "filter",
        "function": "Retiene contaminación sólida para proteger componentes y conservar la limpieza del fluido.",
        "ports": "Entrada y salida",
        "rest": "Siempre en servicio salvo bypass o aislamiento específico.",
        "reading": "Su posición importa: succión, presión, retorno o circuito auxiliar tienen consecuencias diferentes.",
        "field": "Indicador de saturación, bypass, caída de presión, contaminación y especificación del elemento.",
        "failures": ["saturación", "bypass abierto", "elemento incorrecto", "caída de presión alta"],
        "applications": ["presión", "retorno", "offline"],
        "principle": "Filtrar protege el sistema, pero un filtro inadecuado o saturado también puede generar pérdidas y cavitación.",
    },
    "Manómetro": {
        "category": "Medición",
        "symbol": "gauge",
        "function": "Mide la presión local en un punto del circuito.",
        "ports": "Punto de medición",
        "rest": "Indica la presión existente en la conexión donde está instalado.",
        "reading": "La pregunta correcta no es solo 'cuánto marca', sino 'qué parte del sistema estoy midiendo'.",
        "field": "Rango, amortiguación, pulsaciones, aislamiento, calibración y seguridad del punto de prueba.",
        "failures": ["rango inadecuado", "pulsación", "instrumento descalibrado", "conexión incorrecta"],
        "applications": ["diagnóstico", "puesta en marcha", "ajustes"],
        "principle": "La presión es una variable local; dos puntos del mismo circuito pueden tener valores distintos por pérdidas, válvulas o carga.",
    },
    "Cilindro de doble efecto": {
        "category": "Actuadores",
        "symbol": "cylinder_double",
        "function": "Convierte energía hidráulica en fuerza y movimiento lineal en extensión y retracción.",
        "ports": "A y B",
        "rest": "Depende de la válvula que lo gobierna y de la carga externa.",
        "reading": "Diferencie cámara plena y cámara anular: las áreas efectivas no son iguales.",
        "field": "Sellos, rayado de vástago, fugas internas/externas, alineamiento, carga lateral, amortiguación y anclajes.",
        "failures": ["fuga interna", "fuga externa", "vástago dañado", "carga lateral", "aire atrapado"],
        "applications": ["empuje", "elevación", "sujeción", "posicionamiento"],
        "principle": "Para un mismo caudal, la cámara anular produce mayor velocidad y menor fuerza ideal que la cámara plena.",
    },
    "Motor hidráulico": {
        "category": "Actuadores",
        "symbol": "motor_fixed",
        "function": "Convierte energía hidráulica en torque y movimiento rotacional.",
        "ports": "A/B y posible L",
        "rest": "La velocidad y el sentido dependen de caudal y dirección de flujo.",
        "reading": "El triángulo apunta hacia el interior: el fluido entrega energía al componente.",
        "field": "Drenaje de carcasa, contrapresión, velocidad, temperatura, ruido y contaminación.",
        "failures": ["fuga interna", "drenaje alto", "contrapresión", "cavitación"],
        "applications": ["transmisión", "giro", "accionamiento continuo"],
        "principle": "El caudal domina la velocidad y la diferencia de presión domina el torque disponible.",
    },
    "Válvula de alivio": {
        "category": "Control de presión",
        "symbol": "relief",
        "function": "Limita la presión máxima del circuito abriendo una ruta hacia tanque cuando la presión de entrada alcanza el valor de ajuste.",
        "ports": "P y T",
        "rest": "Normalmente cerrada.",
        "reading": "Sensa la presión aguas arriba y compara la fuerza hidráulica con el ajuste del resorte.",
        "field": "Ajuste, descarga continua, vibración, contaminación, temperatura, asiento y línea de retorno.",
        "failures": ["ajuste bajo", "asiento contaminado", "descarga continua", "inestabilidad"],
        "applications": ["protección de presión", "limitación de fuerza", "seguridad del circuito"],
        "principle": "Cuando la fuerza hidráulica supera la fuerza de ajuste, se abre el paso P → T.",
    },
    "Válvula reductora": {
        "category": "Control de presión",
        "symbol": "reducing",
        "function": "Mantiene una presión secundaria menor y controlada aguas abajo, modulando el paso desde la alimentación.",
        "ports": "P/A y drenaje según diseño",
        "rest": "Normalmente abierta.",
        "reading": "La presión controlada se toma aguas abajo; cuando aumenta, la válvula tiende a cerrar y genera una caída de presión.",
        "field": "Presión secundaria, ajuste, drenaje, contaminación, estabilidad y contrapresión.",
        "failures": ["presión secundaria alta", "drenaje bloqueado", "contaminación", "hunting"],
        "applications": ["ramas de menor presión", "sujeción", "circuitos auxiliares"],
        "principle": "No protege el sistema principal como una válvula de alivio; regula una presión aguas abajo.",
    },
    "Válvula antirretorno": {
        "category": "Bloqueo y retención",
        "symbol": "check",
        "function": "Permite flujo en un sentido y bloquea automáticamente el sentido contrario.",
        "ports": "A/B",
        "rest": "Cerrada en el sentido bloqueado; abre cuando la presión vence la carga del obturador/resorte.",
        "reading": "El asiento señala el sentido que queda bloqueado; no interprete el triángulo como flecha de caudal.",
        "field": "Suciedad en asiento, presión de apertura, resorte, fuga inversa y sentido de montaje.",
        "failures": ["fuga inversa", "atasco", "presión de apertura alta", "montaje invertido"],
        "applications": ["retención", "aislamiento", "bypass"],
        "principle": "La diferencia de presión determina si el obturador abre o permanece sobre su asiento.",
    },
    "Antirretorno pilotado": {
        "category": "Bloqueo y retención",
        "symbol": "pilot_check",
        "function": "Retiene la carga como una válvula antirretorno y permite liberar el sentido bloqueado mediante una señal de pilotaje.",
        "ports": "A/B + X",
        "rest": "Bloqueo del sentido inverso hasta recibir pilotaje suficiente.",
        "reading": "Antes de esperar flujo inverso, siga la línea X y confirme de dónde viene la presión de desbloqueo.",
        "field": "Presión piloto, relación de pilotaje, contrapresión, asiento y fugas.",
        "failures": ["pilotaje insuficiente", "contrapresión", "fuga de asiento", "línea X obstruida"],
        "applications": ["retención de cilindros", "bloqueo de carga", "seguridad"],
        "principle": "El pilotaje aplica fuerza sobre un área de control para abrir mecánicamente el obturador.",
    },
    "Control de caudal ajustable": {
        "category": "Control de caudal",
        "symbol": "flow_control",
        "function": "Introduce una restricción ajustable para modificar el caudal que atraviesa una rama y con ello la velocidad de un actuador.",
        "ports": "A/B",
        "rest": "Depende del ajuste de apertura.",
        "reading": "La flecha diagonal indica ajuste. Determine además si el control está en meter-in, meter-out o bleed-off.",
        "field": "Ajuste, caída de presión, contaminación, viscosidad, temperatura y orientación del montaje.",
        "failures": ["orificio contaminado", "ajuste incorrecto", "calentamiento", "caudal inestable"],
        "applications": ["control de velocidad", "amortiguación", "sincronización simple"],
        "principle": "Controlar caudal suele implicar una caída de presión y disipación de potencia.",
    },
    "Regulador unidireccional": {
        "category": "Control de caudal",
        "symbol": "one_way_flow",
        "function": "Regula el caudal en un sentido y permite paso prácticamente libre en el sentido opuesto mediante un bypass con antirretorno.",
        "ports": "A/B",
        "rest": "La rama regulada depende del sentido de montaje.",
        "reading": "Identifique primero el sentido del check; así sabrá cuál recorrido queda estrangulado.",
        "field": "Orientación, ajuste, contaminación, check trabado y presión diferencial.",
        "failures": ["montaje invertido", "check pegado", "restricción contaminada", "caudal errático"],
        "applications": ["meter-in", "meter-out", "control direccional de velocidad"],
        "principle": "Combina dos caminos en paralelo: uno restringido y otro unidireccional.",
    },
}

DIRECTIONAL_VALVES = {
    "2/2 NC": {
        "ports": 2, "positions": 2, "rest": "Cerrada",
        "left": "P bloqueado · A bloqueado", "right": "P → A",
        "use": "Aislar o habilitar una línea.",
    },
    "2/2 NO": {
        "ports": 2, "positions": 2, "rest": "Abierta",
        "left": "P → A", "right": "P bloqueado · A bloqueado",
        "use": "Descarga o paso normalmente disponible.",
    },
    "3/2 NC": {
        "ports": 3, "positions": 2, "rest": "P bloqueado · A → T",
        "left": "P bloqueado · A → T", "right": "P → A · T bloqueado",
        "use": "Gobernar actuadores de simple efecto o señales hidráulicas.",
    },
    "4/2": {
        "ports": 4, "positions": 2, "rest": "Depende del accionamiento",
        "left": "P → A · B → T", "right": "P → B · A → T",
        "use": "Invertir el sentido de un actuador de doble efecto.",
    },
    "4/3 centro cerrado": {
        "ports": 4, "positions": 3, "rest": "Centro cerrado",
        "left": "P → A · B → T", "center": "P, T, A y B bloqueados", "right": "P → B · A → T",
        "use": "Bloquear actuador y alimentación en centro; exige considerar la arquitectura de la bomba.",
    },
    "4/3 centro tándem": {
        "ports": 4, "positions": 3, "rest": "Centro tándem",
        "left": "P → A · B → T", "center": "P → T · A y B bloqueados", "right": "P → B · A → T",
        "use": "Descargar la bomba y mantener bloqueado el actuador en centro.",
    },
    "4/3 centro flotante": {
        "ports": 4, "positions": 3, "rest": "Centro flotante",
        "left": "P → A · B → T", "center": "A y B → T · P bloqueado", "right": "P → B · A → T",
        "use": "Liberar hidráulicamente el actuador hacia tanque manteniendo P bloqueado.",
    },
    "4/3 centro abierto": {
        "ports": 4, "positions": 3, "rest": "Centro abierto",
        "left": "P → A · B → T", "center": "P, A, B y T comunicados", "right": "P → B · A → T",
        "use": "Comunicar los puertos en centro; el comportamiento final depende de carga y arquitectura.",
    },
}

VALVE_FAMILIES = {
    "Dirección": {
        "question": "¿Qué conexiones deben existir entre los puertos en cada estado?",
        "elements": ["2/2", "3/2", "4/2", "4/3"],
        "effect": "Inicio, detención, inversión de movimiento y selección de rutas.",
        "rule": "El número de cuadrados indica posiciones; las líneas y flechas dentro de cada cuadrado muestran conexiones y sentido de flujo.",
    },
    "Presión": {
        "question": "¿Qué presión debe limitarse, reducirse, sostenerse o utilizarse para secuenciar?",
        "elements": ["Alivio", "Reductora", "Secuencia", "Contrabalance"],
        "effect": "Protección, control de fuerza, prioridad y estabilidad de carga.",
        "rule": "Determine primero si el elemento es normalmente abierto o cerrado y desde qué punto sensa la presión.",
    },
    "Caudal": {
        "question": "¿Cuánto flujo debe atravesar una rama y en qué sentido?",
        "elements": ["Estranguladora", "Unidireccional", "Compensada"],
        "effect": "Control de velocidad y reparto de caudal.",
        "rule": "Una restricción controla caudal a costa de una diferencia de presión; la compensación busca estabilizar ese caudal.",
    },
    "Bloqueo": {
        "question": "¿Dónde debe impedirse el flujo inverso o retenerse una carga?",
        "elements": ["Antirretorno", "Antirretorno pilotado", "Doble pilotado"],
        "effect": "Retención, aislamiento y bloqueo de actuadores.",
        "rule": "No basta con seguir una flecha: identifique el sentido libre, el sentido bloqueado y cualquier pilotaje de liberación.",
    },
}

DIAGNOSTICS = {
    "El cilindro no se mueve": [
        "Confirmar que la bomba entrega caudal y que existe alimentación en P.",
        "Leer la posición real de la válvula direccional y comprobar su accionamiento.",
        "Trazar la ruta hasta la cámara que debería presurizarse y verificar que existe retorno desde la cámara opuesta.",
        "Medir presión antes y después del elemento de control; compare con la carga y el ajuste de alivio.",
        "Revisar bloqueo mecánico, carga excesiva o un antirretorno pilotado sin señal de desbloqueo.",
    ],
    "El cilindro está lento en ambos sentidos": [
        "Comparar caudal real de bomba con caudal esperado.",
        "Revisar filtros, succión, temperatura y restricciones comunes a ambos sentidos.",
        "Verificar carrera completa del carrete de la válvula direccional.",
        "Buscar fugas internas relevantes en bomba, válvula o cilindro.",
        "Comprobar si la viscosidad o temperatura están fuera de condición normal.",
    ],
    "El cilindro está lento solo en un sentido": [
        "Seguir exclusivamente la ruta activa de ese movimiento.",
        "Identificar si existe control de caudal, check o antirretorno en esa rama.",
        "Comparar contrapresión de la línea de retorno con el sentido opuesto.",
        "Verificar que el carrete abre completamente en esa posición.",
        "Considerar la diferencia entre área plena y área anular antes de concluir una falla.",
    ],
    "La presión sube al ajuste de alivio": [
        "Confirmar si el actuador llegó a fin de carrera o si la carga quedó mecánicamente bloqueada.",
        "Revisar que exista una ruta de retorno disponible desde el actuador.",
        "Comprobar sobrecarga, agarrotamiento o retención hidráulica no prevista.",
        "Verificar ajuste y estado de la válvula de alivio.",
        "Si el alivio descarga continuamente, investigue además la generación de calor y la arquitectura del centro de la direccional.",
    ],
    "El actuador deriva o no mantiene posición": [
        "Determine si el centro de la válvula realmente bloquea A y B.",
        "Aísle si la fuga es interna del cilindro o cruza por la válvula.",
        "Revise antirretornos pilotados o contrabalance cuando correspondan.",
        "Compruebe pilotaje, contrapresión y posibles fugas externas.",
    ],
    "El sistema se calienta demasiado": [
        "Buscar caudal descargando a alta presión de forma continua.",
        "Revisar estrangulamientos innecesarios y pérdidas de carga elevadas.",
        "Comprobar eficiencia volumétrica de bomba y motores.",
        "Revisar nivel, viscosidad, enfriador, contaminación y aireación.",
        "Confirmar que el centro de la direccional es compatible con el tipo de bomba y la estrategia de descarga.",
    ],
}
