from __future__ import annotations

EXERCISES = [
    {
        "id":"slow_both",
        "title":"Cilindro lento en ambos sentidos",
        "level":"Básico",
        "case":"Un cilindro que normalmente completa su carrera en 8 s ahora tarda 15 s tanto en avance como en retroceso. La presión bajo carga es similar a la histórica.",
        "question":"¿Qué variable conviene comprobar primero?",
        "options":["Aumentar el ajuste de alivio", "Caudal disponible y restricciones comunes", "Cambiar inmediatamente el cilindro", "Bloquear el retorno"],
        "answer":"Caudal disponible y restricciones comunes",
        "explanation":"Si ambos sentidos son lentos y la presión es razonable, la evidencia apunta primero a una reducción de caudal común: bomba, velocidad de accionamiento, filtro/restricción o fuga interna. La velocidad depende de Q/A.",
        "field":"Mida tiempo de ciclo y caudal; compare con presión y temperatura antes de desmontar componentes.",
    },
    {
        "id":"high_p_no_motion",
        "title":"Presión alta, actuador detenido",
        "level":"Básico",
        "case":"Al accionar avance, el manómetro principal sube cerca del ajuste de alivio pero el cilindro no se mueve.",
        "question":"¿Qué lectura es más coherente?",
        "options":["La bomba no genera caudal porque hay presión", "Existe resistencia/carga y debe verificarse la ruta hacia el actuador", "El retorno necesariamente está libre", "La presión alta demuestra que el cilindro está bueno"],
        "answer":"Existe resistencia/carga y debe verificarse la ruta hacia el actuador",
        "explanation":"La presión alta significa que el caudal encuentra resistencia. Hay que verificar conmutación de la válvula, presión A/B, bloqueo mecánico y elementos de retención/control de carga.",
        "field":"Compare P con A/B durante la maniobra; observe si la presión cae al conmutar y vuelve a subir.",
    },
    {
        "id":"counterbalance",
        "title":"Carga vertical que tiende a caer",
        "level":"Intermedio",
        "case":"Un cilindro vertical sostiene una carga. Al ordenar descenso, la carga puede arrastrar al actuador más rápido que el caudal de alimentación.",
        "question":"¿Qué función hidráulica es clave para controlar el descenso?",
        "options":["Válvula de alivio en paralelo con la bomba", "Válvula contrabalance / control de carga", "Filtro de retorno", "Acumulador sin aislamiento"],
        "answer":"Válvula contrabalance / control de carga",
        "explanation":"El control de carga mantiene contrapresión y abre de manera controlada mediante presión/pilotaje, evitando el descenso libre y ayudando a mantener el actuador alimentado.",
        "field":"Mida presión de carga y presión piloto; no ajuste por intuición.",
    },
    {
        "id":"pilot_check",
        "title":"Cilindro bloqueado que no libera",
        "level":"Intermedio",
        "case":"Una retención pilotada mantiene un cilindro inmóvil correctamente, pero al ordenar el movimiento inverso la carga no libera.",
        "question":"¿Qué comprobación tiene mayor valor diagnóstico?",
        "options":["Color del aceite", "Presión piloto en X y contrapresión de drenaje", "Voltaje del motor eléctrico únicamente", "Cambiar el manómetro"],
        "answer":"Presión piloto en X y contrapresión de drenaje",
        "explanation":"Una retención pilotada puede no abrir si el pilotaje es insuficiente, el pistón piloto se atasca o existe una condición de drenaje/contrapresión incompatible.",
        "field":"Compruebe X durante la orden de apertura y compare con la presión de carga que mantiene cerrada la retención.",
    },
    {
        "id":"regen",
        "title":"Regeneración: rápida pero con menos empuje",
        "level":"Intermedio",
        "case":"Durante avance rápido, el lado de vástago se conecta de forma que su caudal se suma al de bomba hacia la cámara plena.",
        "question":"¿Qué combinación describe mejor el efecto?",
        "options":["Menor velocidad y mayor fuerza", "Mayor velocidad y menor fuerza neta", "Mayor velocidad y mayor fuerza máxima siempre", "Sin cambio de velocidad"],
        "answer":"Mayor velocidad y menor fuerza neta",
        "explanation":"El caudal regenerado aumenta el caudal efectivo hacia la cámara plena, pero la presión actúa también sobre el área anular en sentido opuesto; la fuerza neta queda asociada al área diferencial.",
        "field":"Compare velocidad, presión A/B y transición a modo de trabajo cuando aumenta la carga.",
    },
    {
        "id":"cavitation",
        "title":"Bomba ruidosa después de mantenimiento",
        "level":"Intermedio",
        "case":"Tras una intervención la bomba presenta ruido, el movimiento es irregular y aparece espuma en el tanque.",
        "question":"¿Qué zona se revisa primero?",
        "options":["Línea de succión, nivel, respiradero y fittings", "Ajuste máximo del alivio", "Pintura del depósito", "Solo el cilindro"],
        "answer":"Línea de succión, nivel, respiradero y fittings",
        "explanation":"Las restricciones o entradas de aire en succión son causas frecuentes de cavitación/aireación. La inspección debe empezar por lo simple y visible antes de desmontar la bomba.",
        "field":"Revise vacío/restricción de entrada, uniones, nivel y condición del fluido.",
    },
    {
        "id":"ls_blocked",
        "title":"Implemento LS pierde respuesta",
        "level":"Avanzado",
        "case":"En un cargador con bomba load-sensing el implemento se mueve muy lento bajo carga. La bomba mantiene standby, pero la presión LS no sigue a la carga.",
        "question":"¿Qué hipótesis gana fuerza?",
        "options":["Señal LS ausente/restringida o shuttle defectuoso", "El tanque tiene demasiado aceite", "El cilindro es demasiado grande por definición", "El retorno siempre debe estar a alta presión"],
        "answer":"Señal LS ausente/restringida o shuttle defectuoso",
        "explanation":"El control LS necesita recibir la presión de carga para elevar la presión de bomba por encima de ella y mantener el margen. Una señal perdida puede dejar la bomba cerca de standby.",
        "field":"Compare presión de trabajo con LS y presión de bomba; revise continuidad de la galería LS/shuttle.",
    },
    {
        "id":"hot_component",
        "title":"Sistema se calienta sin trabajo útil",
        "level":"Avanzado",
        "case":"La máquina desarrolla temperatura alta. Una termografía muestra una válvula mucho más caliente que el resto del circuito.",
        "question":"¿Qué interpretación es más útil?",
        "options":["El calor identifica por sí solo la pieza que debe cambiarse", "Probablemente existe una caída de presión con caudal a través de esa zona; hay que medir", "Todo sistema caliente tiene cavitación", "Aumentar viscosidad siempre resuelve"],
        "answer":"Probablemente existe una caída de presión con caudal a través de esa zona; hay que medir",
        "explanation":"Una pérdida de potencia hidráulica (Δp·Q) se transforma en calor. La temperatura orienta, pero debe confirmarse con presión/caudal y estado funcional.",
        "field":"Mida presión antes/después y determine si hay caudal no útil por alivio, restricción o fuga interna.",
    },
]

LEARNING_PATH = [
    ("1", "Reconocer", "Identificar líneas, puertos y familias de símbolos sin memorizar circuitos completos."),
    ("2", "Descomponer", "Leer cada válvula por vías, posiciones, centro y accionamiento."),
    ("3", "Trazar", "Seguir el recorrido del aceite en cada estado: P → control → actuador → T."),
    ("4", "Predecir", "Anticipar movimiento, presión, caudal y puntos de medición antes de tocar la máquina."),
    ("5", "Relacionar", "Ubicar en el modelo físico el actuador, las líneas y el componente que aparece en el plano."),
    ("6", "Diagnosticar", "Separar síntoma de causa y comprobar hipótesis con evidencia de terreno."),
]
